In [ ]:
import cv2
img = cv2.imread('C:/Users/bayuk/Downloads/WhatsApp Image 2023-03-07 at 16.59.16.jpeg')
cv2.imshow('bayu', img)
cv2.waitKey()
cv2.imshow('bayu0', img[:,:,0])
cv2.waitKey()
cv2.imshow('bayu1', img[:,:,1])
cv2.waitKey()
cv2.imshow('bayu2', img[:,:,2])
cv2.waitKey()



In [2]:
print('bayu', img) 
cv2.waitKey()
print('bayu0', img[:,:,0])
cv2.waitKey()
print('bayu1', img[:,:,1])
cv2.waitKey()
print('bayu2', img[:,:,2])
cv2.waitKey()

bayu [[[255 254 255]
  [255 254 255]
  [255 254 255]
  ...
  [ 63  85  56]
  [ 72  92  63]
  [ 82 100  69]]

 [[255 254 255]
  [255 254 255]
  [255 254 255]
  ...
  [ 65  87  58]
  [ 75  96  64]
  [ 84 102  71]]

 [[255 254 255]
  [255 254 255]
  [255 254 255]
  ...
  [ 68  90  61]
  [ 76  97  65]
  [ 84 105  72]]

 ...

 [[111 105 106]
  [111 105 106]
  [112 104 105]
  ...
  [ 58  72  60]
  [ 58  75  62]
  [ 58  75  62]]

 [[110 104 105]
  [109 103 104]
  [109 103 104]
  ...
  [ 59  73  61]
  [ 58  75  62]
  [ 58  75  62]]

 [[108 102 103]
  [108 102 103]
  [107 101 102]
  ...
  [ 60  74  62]
  [ 58  75  62]
  [ 59  76  63]]]
bayu0 [[255 255 255 ...  63  72  82]
 [255 255 255 ...  65  75  84]
 [255 255 255 ...  68  76  84]
 ...
 [111 111 112 ...  58  58  58]
 [110 109 109 ...  59  58  58]
 [108 108 107 ...  60  58  59]]
bayu1 [[254 254 254 ...  85  92 100]
 [254 254 254 ...  87  96 102]
 [254 254 254 ...  90  97 105]
 ...
 [105 105 104 ...  72  75  75]
 [104 103 103 ...  73  75  75]
 

-1

In [3]:
print(img.shape)
print(img.size)
print(img.dtype)

(1600, 1066, 3)
5116800
uint8


In [4]:
# Band blue, green dan red masng-masing disimpan pada variabel b,g,r
b, g, r = cv2.split(img)
print(b)
print(g)
print(r)

[[255 255 255 ...  63  72  82]
 [255 255 255 ...  65  75  84]
 [255 255 255 ...  68  76  84]
 ...
 [111 111 112 ...  58  58  58]
 [110 109 109 ...  59  58  58]
 [108 108 107 ...  60  58  59]]
[[254 254 254 ...  85  92 100]
 [254 254 254 ...  87  96 102]
 [254 254 254 ...  90  97 105]
 ...
 [105 105 104 ...  72  75  75]
 [104 103 103 ...  73  75  75]
 [102 102 101 ...  74  75  76]]
[[255 255 255 ...  56  63  69]
 [255 255 255 ...  58  64  71]
 [255 255 255 ...  61  65  72]
 ...
 [106 106 105 ...  60  62  62]
 [105 104 104 ...  61  62  62]
 [103 103 102 ...  62  62  63]]


In [5]:
img=cv2.imread('C:/Users/bayuk/Downloads/WhatsApp Image 2023-03-07 at 16.59.16.jpeg')
imageGray = cv2. cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("bayu",imageGray)
cv2.waitKey()


-1

In [6]:
img=cv2.imread("C:/Users/bayuk/Downloads/WhatsApp Image 2023-03-07 at 16.59.16.jpeg")
resize = cv2.resize(img, (200, 200)) # Resize image to 200x200 pixel
cv2.imshow("bayu", resize)
cv2.waitKey(0)
#cv2.destroyAllWindows()


-1

In [7]:
img=cv2.imread("C:/Users/bayuk/Downloads/WhatsApp Image 2023-03-07 at 16.59.16.jpeg")
resize = cv2.resize(img, (int(img.shape[0]*2), int(img.shape[1]*2))) 
# mengubah ukuran citra menajadi 2x ukuran citra asli
cv2.imshow("bayu", resize)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [8]:
img=cv2.imread("C:/Users/bayuk/Downloads/WhatsApp Image 2023-03-07 at 16.59.16.jpeg")
#menyompan hasil modifikasi citra
resize = cv2.resize(img, (int(img.shape[0]*2), int(img.shape[1]*2))) 
# mengubah ukuran citra menajadi 2x ukuran citra asli
cv2.imshow("bayu resize", resize)
cv2.imwrite("bayu_resize.jpg", resize)
 # menyimpan citra baru yang sudah diperbesar 2x
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
import cv2
img=cv2.imread("C:/Users/bayuk/Downloads/WhatsApp Image 2023-03-07 at 16.59.16.jpeg")
cv2.imshow('Hasil Inversi',img)
hasil = 255-img
cv2.imshow('Hasil Inversi',hasil)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
cv.calcHist(images, channels, mask, histSize, ranges[, hist[, accumulate]])


In [ ]:
# memanggil library yang dibutuhkan
import cv2
import numpy as np
from matplotlib import pyplot as plt
img=cv2.imread("C:/Users/bayuk/Downloads/WhatsApp Image 2023-03-07 at 16.59.16.jpeg")
color = ('b','g','r')
for i,col in enumerate(color):
      histr = cv2.calcHist([img],[i],None,[256],[0,256])
      plt.plot(histr,color = col)
      plt.xlim([0,256])
plt.show()

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
img = cv2.imread("C:/Users/bayuk/Downloads/WhatsApp Image 2023-03-07 at 16.59.16.jpeg")
hist,bins =np.histogram(img.flatten(),256,[0,256])
cdf = hist.cumsum()
cdf_normalized = cdf * hist.max()/cdf.max()
plt.plot(cdf_normalized, color ='b')
plt.hist(img.flatten(),256,[0,256],color = 'r')
plt.xlim([0,256])
plt.legend(('cdf','histogram'), loc= 'upper left')
plt.show()
